### 1. /api/s05/quality/summary

GET localhost:8080/api/s05/quality/summary

### 2. /api/s05/role/separated

GET localhost:8080/api/s05/role/separated

### 3. /api/s05/role/anti-pattern

GET localhost:8080/api/s05/role/anti-pattern